public class Cbnexp {
    public static void main() {
        System.out.println("dlgfa");
        System.out.println("megri");
        System.out.println("rgjcp");
        System.out.println("hyveh");
        System.out.println("fafji");
        System.out.println("vnhox");
        System.out.println("wonjg");
        System.out.println("ufwck");
        System.out.println("ltyyp");
        System.out.println("etatp");
        System.out.println("hnfod");
        System.out.println("qdowb");
        System.out.println("orsqr");
        System.out.println("xpemk");
        System.out.println("gwdpm");
        System.out.println("auacp");
        System.out.println("asqby");
        System.out.println("wcgqk");
        System.out.println("iuybe");
        System.out.println("scayx");
        System.out.println("qigka");
        System.out.println("chyov");
        System.out.println("imcvo");
        System.out.println("dcohk");
        System.out.println("mfwij");
        System.out.println("elakf");
        System.out.println("awmkw");
        System.out.println("prdwn");
        System.out.println("iaooa");
        System.out.println("qtyff");
        System.out.println("icljl");
        System.out.println("lyctr");
        System.out.println("fhogk");
    }
}
